---
- hosts: confluent
  become: true
  roles:
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
  tasks:
    - name: "Get the confluent rpm key"
      rpm_key:
        state: present
        key: http://packages.confluent.io/rpm/4.0/archive.key
      tags:
        - confluent
    - name: "Add Confluent.dist to yum"
      yum_repository:
        name: Confluent.dist
        description: Confluent repository (dist)
        baseurl: https://packages.confluent.io/rpm/4.0/7
        gpgcheck: yes
        gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
        enabled: yes
        file: confluent
      tags:
        - confluent
    - name: "Add Confluent"
      yum_repository:
        name: Confluent
        description: Confluent repository
        baseurl: https://packages.confluent.io/rpm/4.0
        gpgcheck: yes
        gpgkey: https://packages.confluent.io/rpm/4.0/archive.key
        enabled: yes
        file: confluent
      tags:
        - confluent
    - name: "Clear yum cache"
      command: yum clean all
      tags:
        - confluent
    - name: Install Confluent
      yum:
        name: confluent-platform-oss-2.11
        state: installed
      tags:
        - confluent
