---
- hosts: kafka
  tags:
    -kafka
  become: true
  vars:
    kafka_config_directory: /etc/kafka
    kafka_config_filename: server.properties
  tasks:
    - include_vars:
        file: 'vars/kafka.yml'
    - set_fact:
        host_and_port: '{{ item }}:2181'
      with_items:
        - "{{ zookeeper_ensemble }}"
      register: zookeeper_servers
    - name: "Upload kafka properties"
      template:
        src: files/kafka/server.properties.j2
        dest: "{{ kafka_config_directory }}/{{ kafka_config_filename }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Add systemd service file"
      template:
        src: files/kafka/kafka.service.j2
        dest: /etc/systemd/system/kafka.service
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Enable and start kafka service"
      systemd:
        name: kafka
        enabled: yes
        state: started
