---
- hosts: kafka
  become: true
  roles:
    - role: ipset
      ipset_rule_names:
        - user_defined_allowed
      ipset_ips:
        - "zk-01.umn.edu,tcp:9092"
        - "zk-02.umn.edu,tcp:9092"
        - "zk-03.umn.edu,tcp:9092"
  tasks:
    - set_fact:
        host_and_port: '{{ item }}:2181'
      with_items:
        - "{{ groups['zookeeper'] }}"
      register: zookeeper_servers
      tags:
        - kafka
    - name: "Upload kafka properties"
      template:
        src: files/kafka/server.properties.j2
        dest: /etc/kafka/server.properties
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      tags:
        - kafka
