---
- hosts: schema-registry
  tags:
    - schema-registry
  become: true
  vars:
    schema_registry_config_directory: /etc/schema-registry
    schema_registry_config_filename: schema-registry.properties
  tasks:
    - include_vars:
        file: 'vars/kafka.yml'
    - set_fact:
        host_and_port: '{{ item }}:9092'
      with_items:
        - "{{ kafka_cluster }}"
      register: kafka_servers
    - set_fact:
        host_and_port: '{{ item }}:2181'
      with_items:
        - "{{ zookeeper_ensemble }}"
      register: zookeeper_servers
    - name: "Upload Schema Registry properties"
      template:
        src: files/schema-registry/schema-registry.properties.j2
        dest: "{{ schema_registry_config_directory }}/{{ schema_registry_config_filename }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Add systemd service file"
      template:
        src: files/schema-registry/schema-registry.service.j2
        dest: /etc/systemd/system/schema-registry.service
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Enable and start schema-registry service"
      systemd:
        name: schema-registry
        enabled: yes
        state: started
- import_playbook: kc_schema_registry_ports_flush.yml
- import_playbook: kc_schema_registry_ports_open.yml
