---
- hosts: zookeeper
  tags:
    - zookeeper
  become: true
  vars:
    zookeeper_data_directory: /var/lib/zookeeper
    zookeeper_config_directory: /etc/kafka/
    zookeeper_config_filename: zookeeper.properties
  tasks:
    - include_vars:
        file: 'vars/kafka.yml'
    - name: "Upload zookeeper properties"
      template:
        src: files/zookeeper/zookeeper.properties.j2
        dest: "{{ zookeeper_config_directory }}/{{ zookeeper_config_filename }}"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Create zookeeper directory"
      file:
        dest: "{{ zookeeper_data_directory }}"
        state: directory
        owner: root
        group: root
    - name: "Identify server"
      template:
        src: files/zookeeper/myid.j2
        dest: "{{ zookeeper_data_directory }}/myid"
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Add systemd service file"
      template:
        src: files/zookeeper/zookeeper.service.j2
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: "Enable and start zookeeper service"
      systemd:
        name: zookeeper
        enabled: yes
        state: started
- import_playbook: kc_user_defined_ports_flush.yml
- import_playbook: kc_user_defined_ports_open.yml
